#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Aug 08 14:46:22 AEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Hysteria-Shaders-Universal-v1.2.2.zip
